# 日志哨兵配置文件

# 监控的日志文件列表
log_files:
  # 应用日志
  - path: "/var/log/app/application.log"
    keywords:
      - "ERROR"
      - "FATAL"
      - "Exception"
      - "panic"
    enabled: true

  # 系统日志
  - path: "/var/log/system.log"
    keywords:
      - "error"
      - "failed"
      - "timeout"
    enabled: true

  # Nginx错误日志
  - path: "/var/log/nginx/error.log"
    keywords:
      - "error"
      - "alert"
      - "emerg"
    enabled: false

# 通知器配置
notifiers:
  # 飞书机器人
  - type: "feishu"
    webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/your-webhook-url"
    enabled: true

  # 钉钉机器人（带签名）
  - type: "dingtalk"
    webhook: "https://oapi.dingtalk.com/robot/send?access_token=your-access-token"
    secret: "your-secret-key"
    enabled: false

  # 钉钉机器人（不带签名）
  - type: "dingtalk"
    webhook: "https://oapi.dingtalk.com/robot/send?access_token=your-access-token"
    enabled: false